---
title: "project"
author: "Sanjana Agrawal"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
prior <- function() {
  return(runif(1))
}
```


```{r}
# Generate probability matrix
prob_matrix <- function(qc, qh, n) {
  #' Returns a nxn matrix of probabilities given two values
  #' 
  #' @param qc probability 1
  #' @param qh probability 2
  #' @param n number of rows and columns
  #' @return matrix of probabilities
  
  # Initialize matrix with row/col starting at 0
  W = matrix(0, nrow = n+1, ncol = n+1)
  
  # First row is qc^s, s = 0, 1, ..., n
  W[1,] = qc^(0:n)
  
  # Subsequent rows
  for (j in 2:(n+1)) {
    for (i in j:(n+1)) {
      if (i == j) {
        W[j,j] <- 1 - sum(W[1:(j-1), j])
      }
      else {
        W[j, i] <- choose(i-1,j-1) * W[j,j] * (qc*qh^(j-1))^(i-j)
      }
    }
  }
  
  return(W[, -1])
  
}
```


```{r}
obs_matrix1 <- matrix(c(66, 87, 25, 22, 4,
                     13, 14, 15, 9, 4,
                     0, 4, 4, 9, 1,
                     0, 0, 4, 3, 1,
                     0, 0, 0, 1, 1,
                     0, 0, 0, 0, 0), nrow = 6, byrow = TRUE)

obs_matrix2 <- matrix(c(44, 62, 47, 38, 9,
                     10, 13, 8, 11, 5,
                     0, 9, 2, 7, 3,
                     0, 0, 3, 5, 1,
                     0, 0, 0, 1, 0,
                     0, 0, 0, 0, 1), nrow = 6, byrow = TRUE)

obs_matrix3 <- matrix(c(9, 12, 18, 9, 4,
                     1, 6, 6, 4, 3,
                     0, 2, 3, 4, 0,
                     0, 0, 1, 3, 3,
                     0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0), nrow = 6, byrow = TRUE)

obs_matrix4 <- matrix(c(15, 12, 4,
                     11, 17, 4,
                     0, 21, 4,
                     0, 0, 5), nrow = 4, byrow = TRUE)


```


```{r}
# Function to sample data from the matrix distribution
sample_from_matrix_distribution <- function(prob_matrix, obs_matrix) {
  sampled_data <- matrix(0, nrow = nrow(obs_matrix), ncol = ncol(obs_matrix))
  
  for (c in 1:ncol(sampled_data)) {
    sim_vector <- rmultinom(1, sum(obs_matrix[,c]), prob = prob_matrix[,c])
    sampled_data[,c] <- sim_vector
  }
  
  return(sampled_data)
}
```


```{r}
# Sample from the matrix distribution
W <- prob_matrix(0.8, 0.2, 5)
sampled_data <- sample_from_matrix_distribution(W, obs_matrix1)
print(sampled_data)
```


```{r}
abc_sim <- function(obs_data, prior, tolerance, n_steps) {
  qc_accepted <- c()
  qh_accepted <- c()
  for (i in 1:n_steps) {
    qc <- prior()
    qh <- prior()
    n = ncol(obs_data)
    W <- prob_matrix(qc, qh, n)
    sim_data <- sample_from_matrix_distribution(W, obs_data)
    if (norm(obs_data - sim_data, "F") <= tolerance) {
      qc_accepted <- append(qc_accepted, qc)
      qh_accepted <- append(qh_accepted, qh)
    }
  }
  #print(qh_accepted)
  #print(qc_accepted)
  plot(qh_accepted, qc_accepted, col='red', xlim=c(0,1), ylim=c(0,1))
}
```


```{r}
abc_sim_both <- function(obs_data1, obs_data2, prior, tolerance, n_steps) {
  print(obs_data1)
  qc1_accepted <- c()
  qh1_accepted <- c()
  qc2_accepted <- c()
  qh2_accepted <- c()
  for (i in 1:n_steps) {
    qc1 <- prior()
    qh1 <- prior()
    qc2 <- prior()
    qh2 <- prior()
    n1 = ncol(obs_data1)
    n2 = ncol(obs_data2)
    W1 <- prob_matrix(qc1, qh1, n1)
    W2 <- prob_matrix(qc2, qh2, n2)
    sim_data1 <- sample_from_matrix_distribution(W1, obs_data1)
    sim_data2 <- sample_from_matrix_distribution(W2, obs_data2)
    #cat("\n", sprintf("%i iteration", i), "\n")
    #print(sim_data)
    #print(norm(obs_data1 - sim_data, "F"))
    if ((norm(obs_data1 - sim_data1, "F") + norm(obs_data2 - sim_data2, "F"))/2 <= tolerance) {
      qc1_accepted <- append(qc1_accepted, qc1)
      qh1_accepted <- append(qh1_accepted, qh1)
      qc2_accepted <- append(qc2_accepted, qc2)
      qh2_accepted <- append(qh2_accepted, qh2)
    }
  }
  plot(qh1_accepted, qc1_accepted, col='red', xlim=c(0,1), ylim=c(0,1))
  plot(qh2_accepted, qc2_accepted, col='blue', xlim=c(0,1), ylim=c(0,1))
}
```



```{r}
abc_sim(obs_matrix4, prior, 10, 100000)

```


```{r}
abc_sim_both(obs_matrix1, obs_matrix2, prior, 20, 100000)
```


```{r}
abc_smc <- function(obs_data, prior, tolerance, n_steps) {
  n = ncol(obs_data)
  for (i in 1:length(tolerance)) {
    accepted_qc <- c()
    accepted_qh <- c()
    acc_count <- 0
    while (acc_count < n_steps) {
      if (i == 1) {
        qc <- prior()
        qh <- prior()
      }
      else {
        qc <- sample(qc_population, 1)
        qh <- sample(qh_population, 1)
      }
      W <- prob_matrix(qc, qh, n)
      sim_data <- sample_from_matrix_distribution(W, obs_data)
      if (norm(obs_data - sim_data, "F") <= tolerance[i]) {
        accepted_qc <- append(accepted_qc, qc)
        accepted_qh <- append(accepted_qh, qc)
        acc_count <- acc_count + 1
      }
    }
    qc_population <- accepted_qc
    qh_population <- accepted_qh
  }
  plot(accepted_qh, accepted_qc, col="red", xlim=c(0,1), ylim=c(0,1))
}
```


```{r}
abc_smc(obs_matrix2, prior, c(80, 50, 30, 20, 15, 13, 12), 10000)
```
```{r}
abc_smc(obs_matrix4, prior, c(40, 20, 15, 10, 8, 6, 5), 1000)
```


```{r}
abc_smc_both <- function(obs_data1, obs_data2, prior, tolerance, n_steps) {
  n1 = ncol(obs_data1)
  n2 = ncol(obs_data2)
  for (i in 1:(length(tolerance)-1)) {
    accepted_qc1 <- c()
    accepted_qh1 <- c()
    accepted_qc2 <- c()
    accepted_qh2 <- c()
    acc_count <- 0
    while (acc_count < n_steps) {
      if (i == 1) {
        qc1 <- prior()
        qh1 <- prior()
        qc2 <- prior()
        qh2 <- prior()
      }
      else {
        qc1 <- sample(qc1_population, 1)
        qh1 <- sample(qh1_population, 1)
        qc2 <- sample(qc2_population, 1)
        qh2 <- sample(qh2_population, 1)
      }
      W1 <- prob_matrix(qc1, qh1, n1)
      W2 <- prob_matrix(qc2, qh2, n2)
      sim_data1 <- sample_from_matrix_distribution(W1, obs_data1)
      sim_data2 <- sample_from_matrix_distribution(W2, obs_data2)
      if ((norm(obs_data1 - sim_data1, "F") + norm(obs_data2 - sim_data2, "F"))/2 <= tolerance[i]) {
        accepted_qc1 <- append(accepted_qc1, qc1)
        accepted_qh1 <- append(accepted_qh1, qc1)
        accepted_qc2 <- append(accepted_qc2, qc2)
        accepted_qh2 <- append(accepted_qh2, qc2)
        acc_count <- acc_count + 1
      }
    }
    qc1_population <- accepted_qc1
    qh1_population <- accepted_qh1
    qc2_population <- accepted_qc2
    qh2_population <- accepted_qh2
  }
  plot(accepted_qh1, accepted_qc1, col="red", xlim=c(0,1), ylim=c(0,1))
  plot(accepted_qh2, accepted_qc2, col="blue", xlim=c(0,1), ylim=c(0,1))
}
```


```{r}
abc_smc_both(obs_matrix1, obs_matrix2, prior, c(100, 80, 50, 30, 20, 15, 13, 12), 100000)
```

```{r}
abc_smc_both(obs_matrix3, obs_matrix4, prior, c(40, 20, 15, 10, 8, 6, 5), 1000)
```

```{r}
kernel <- function(population, particle) {
  max_val <- max(population)
  min_val <- min(population)
  sigma <- 0.5*(max_val - min_val)
  return(particle + runif(1, -sigma, sigma))
}
```


```{r}
prior_pdf <- function(x) {
  return(x >= 0 && x <= 1)
}
```

```{r}
prior_pdf(3)
```


```{r}
get_param_sample <- function(population, prior_pdf) {
  while (TRUE) {
    particle <- sample(population, 1)
    perturbed <- kernel(population, particle)
    if (prior_pdf(perturbed)) {
      return(perturbed)
    }
  }
}
```


```{r}
abc_smc_perturbation <- function(obs_data1, obs_data2, prior, tolerance, n_steps) {
  n1 = ncol(obs_data1)
  n2 = ncol(obs_data2)
  for (i in 1:(length(tolerance)-1)) {
    accepted_qc1 <- c()
    accepted_qh1 <- c()
    accepted_qc2 <- c()
    accepted_qh2 <- c()
    acc_count <- 0
    while (acc_count < n_steps) {
      if (i == 1) {
        qc1 <- prior()
        qh1 <- prior()
        qc2 <- prior()
        qh2 <- prior()
      }
      else {
        qc1 <- get_param_sample(qc1_population, prior_pdf)
        qh1 <- get_param_sample(qh1_population, prior_pdf)
        qc2 <- get_param_sample(qc2_population, prior_pdf)
        qh2 <- get_param_sample(qh2_population, prior_pdf)
      }
      W1 <- prob_matrix(qc1, qh1, n1)
      W2 <- prob_matrix(qc2, qh2, n2)
      sim_data1 <- sample_from_matrix_distribution(W1, obs_data1)
      sim_data2 <- sample_from_matrix_distribution(W2, obs_data2)
      if ((norm(obs_data1 - sim_data1, "F") + norm(obs_data2 - sim_data2, "F"))/2 <= tolerance[i]) {
        accepted_qc1 <- append(accepted_qc1, qc1)
        accepted_qh1 <- append(accepted_qh1, qc1)
        accepted_qc2 <- append(accepted_qc2, qc2)
        accepted_qh2 <- append(accepted_qh2, qc2)
        acc_count <- acc_count + 1
      }
    }
    qc1_population <- accepted_qc1
    qh1_population <- accepted_qh1
    qc2_population <- accepted_qc2
    qh2_population <- accepted_qh2
  }
  plot(accepted_qh1, accepted_qc1, col="red", xlim=c(0,1), ylim=c(0,1))
  plot(accepted_qh2, accepted_qc2, col="blue", xlim=c(0,1), ylim=c(0,1))
}
```


```{r}
abc_smc_perturbation(obs_matrix1, obs_matrix2, prior, c(100, 80, 50, 30, 20, 15, 13, 12), 1000)
```

```{r}
abc_smc_perturbation(obs_matrix3, obs_matrix4, prior, c(40, 20, 15, 10, 8, 6, 5), 1000)
```

